language: java
install: ./gradlew clean test
before_install:
 - cd ..
 - git clone https://github.com/Canadensys/narwhal-processor.git
 - cd narwhal-processor
 - git fetch --tags
 - git checkout tags/1.5.2
 - mvn -Dhttps.protocols=TLSv1.2 clean install

# jdk7 requires Precise, see https://github.com/travis-ci/travis-ci/issues/8503
matrix:
 include:
  - jdk: oraclejdk8
    dist: trusty
  - jdk: oraclejdk7
    dist: precise
  - jdk: openjdk7
    dist: precise

# openjdk7 requires hostname see https://github.com/travis-ci/travis-ci/issues/5227
addons:
 hostname: narhwalapi
